name: Pipeline
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - name: Release
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "::set-env name=BUMP_VERSION::$(yarn bump)"
          echo "${{env.BUMP_VERSION}}"
          yarn version --patch --no-git-tag-version
          echo "::set-env name=CURRENT_VERSION::$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')"
          echo $env.CURRENT_VERSION
          yarn changelog
          git tag $env.CURRENT_VERSION}
          git add .
          git commit -m 'chore(release): "${{env.CURRENT_VERSION}}"'
          git push --follow-tags
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
