name: Pipeline
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - name: Check Version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "::set-env name=BUMP_VERSION::$(yarn -s bump)"
      - name: Bump Version & Changelog
        run: |
          yarn version --${{env.BUMP_VERSION}} --no-git-tag-version
          yarn changelog
          echo "::set-env name=NEW_VERSION::$(yarn -s package-version)"
      - name: Release
        run: |
          git add .
          git commit -m 'chore(release): ${{env.NEW_VERSION}}'
          git tag v${{env.NEW_VERSION}}
          git push --follow-tags
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
